---
- name: moves tar file to one of the pi servers
  hosts: localhost
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ~/ansible/README.md
        dest: ~/README.md
        owner: bob
        group: bob
        mode: '0644'

