---
- name: Check if a service is running
  hosts: _PI_SERVER
  become: true  # Run tasks with sudo (root) privileges
  gather_facts: false
  vars:
    SERVICE: auditd

  tasks:
    - name: Check if the service is running
      systemd:
        state: started
        name: "{{ SERVICE }}"
      register: service_status

    - name: Display the service status
      debug:
        var: service_status
