---
- name: update and upgrade distro
  hosts: _PI_SERVER          # put the ip of group of host 
  gather_facts: false       # Disable gathering facts to speed up the execution
  become: true
  tasks:
    # - name: Run the equivalent of "apt-get update" as a separate step
    #ansible.builtin.apt:
    #    update_cache: yes
    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist
